package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/perplexityai/numbat/internal/finding"
	"github.com/perplexityai/numbat/internal/hook"
	"github.com/perplexityai/numbat/internal/model"
	"github.com/perplexityai/numbat/internal/output"
	"github.com/perplexityai/numbat/internal/pipeline"
	"github.com/perplexityai/numbat/internal/rule"
	"github.com/perplexityai/numbat/internal/sequence"
	"github.com/perplexityai/numbat/internal/state"
)

// Hook handlers run on an agent's critical path. Keep direct HTTP delivery
// bounded well below the common 10-second tool-hook timeout; scans and the
// long-running collector retain their 30-second default.
const defaultHookHTTPTimeout = 5 * time.Second

// noDecisionMessage is the only enforce-mode failure detail written to the
// invoking host. Once open, the operator-facing record sink carries available
// diagnostics.
const noDecisionMessage = "hook: no decision returned"

// runHook dispatches the `hook` subcommand group: the live handler
// (`numbat hook <event> --agent ...`) and the installer
// (`numbat hook install|uninstall|status`).
func runHook(args []string, stdin io.Reader, stdout, stderr io.Writer) int {
	if len(args) == 0 {
		fmt.Fprintln(stderr, "usage: numbat hook EVENT|install|uninstall|status [flags]")
		return 2
	}
	switch args[0] {
	case "install", "uninstall", "status":
		return runHookAdmin(args[0], args[1:], stdout, stderr)
	case "-h", "--help", "help":
		hookUsage(stdout)
		return 0
	default:
		return runHookEvent(args[0], args[1:], stdin, stdout, stderr)
	}
}

func hookUsage(w io.Writer) {
	fmt.Fprintf(w, `usage:
  numbat hook EVENT --agent NAME [output flags]  handle one live integration callback
  numbat hook install --agent NAME|all           install numbat's live integrations
  numbat hook uninstall --agent NAME|all         remove numbat-owned live integrations
  numbat hook status [--agent NAME|all]          inspect numbat-owned configuration

agents: %s

The EVENT form is the integration entry point generated by "hook install";
it is not normally invoked by hand. Event names follow each agent's hook
contract. See docs/live-capture.md for setup and coverage.

modes:
  monitor (default): detect and record; never deny; preserve the host's normal
    permission flow
  enforce (--enforce): deny supported pre-action requests when a rule marked
    enforce=true matches; fail open on decision errors

Trust, consent, activation, and restart requirements vary by agent. Hook status
does not verify execution or record delivery; see
docs/deployment.md#hook-trust-and-activation.
`, hook.AgentUsage())
}

// runHookEvent normalizes one callback and runs the shared detection pipeline.
// Failures relevant to a decision fail open. The EVENT form is an agent
// callback, so even malformed installed arguments return success.
func runHookEvent(event string, args []string, stdin io.Reader, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("hook", flag.ContinueOnError)
	fs.SetOutput(stderr)
	agentFlag := fs.String("agent", "", "source agent: "+hook.AgentUsage()+" (required)")
	caseID := fs.String("case-id", "", "case identifier stamped on every emitted event and derived finding")
	var emitValues multiFlag
	fs.Var(&emitValues, "emit", emitFlagHelp()+"; enforce mode requires findings")
	contentFlag := fs.String("content", "preview", contentFlagHelp())
	includeReasoning := fs.Bool("include-reasoning", false, "include source-recorded reasoning events when the integration exposes them")
	var outputValues multiFlag
	fs.Var(&outputValues, "output", outputFlagHelp(outputModeStdout)+". stdout mode writes records to hook stderr and is unavailable in enforce mode")
	outputFile := fs.String("output-file", "", "destination path (required when --output includes file)")
	spoolFile := fs.String("spool-file", "", "durable queue path (required when --output includes spool)")
	httpURL := fs.String("http-url", "", "ingest URL (required when --output includes http)")
	httpBatch := fs.Int("http-batch-size", 500, "records per HTTP POST")
	httpTimeout := fs.Duration("http-timeout", defaultHookHTTPTimeout, "HTTP request timeout")
	httpAuth := fs.String("http-auth", output.AuthNone, "HTTP delivery auth: none|bearer|hmac-sha256")
	httpSigHeader := fs.String("http-sig-header", output.DefaultHMACHeader, "header carrying the hmac-sha256 signature")
	httpTSHeader := fs.String("http-timestamp-header", output.DefaultTimestampHeader, "header carrying the signed timestamp")
	httpAllowInsecure := fs.Bool("http-allow-insecure", false, "allow plain http to non-loopback hosts")
	httpGzip := fs.Bool("http-gzip", false, "gzip the HTTP POST body")
	// Stable installer provenance; accepted but inert at runtime.
	_ = fs.String("installed-by", "", "provenance marker set by hook install (ignored at runtime)")
	stateDB := fs.String("state-db", "", "bbolt file holding live sequence-window state (default $HOME/.numbat/state.db)")
	// Enforcement blocks only a rule marked enforce=true after its decision path
	// completes cleanly. Unavailable correlation state affects sequence rules only.
	enforceFlag := fs.Bool("enforce", false, "enforce mode: deny supported pre-action requests when a rule marked enforce=true matches (opt-in; default is monitor: detection-only, never blocks)")
	var rf ruleFlags
	rf.register(fs)
	fs.Usage = func() {
		fmt.Fprintln(stderr, "usage: numbat hook EVENT --agent "+hook.AgentUsage()+" [--emit KIND ...] [--content preview|full] [--include-reasoning] [--output SINK ...] [--case-id ID] [--rules-dir DIR ...] [--no-builtin-rules]")
		printHTTPAuthEnvHelp(stderr, false)
		fs.PrintDefaults()
	}

	// Usage errors indicate a broken hook command and do not emit a passthrough.
	// Malformed payloads and decision-relevant processing failures below fail open.
	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return 0
		}
		return 0
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "hook: unexpected argument %q\n", fs.Arg(0))
		return 0
	}
	if *agentFlag == "" {
		fmt.Fprintln(stderr, "hook: --agent is required ("+hook.AgentUsage()+")")
		return 0
	}
	sourceAgent, err := hook.ParseAgent(*agentFlag)
	if err != nil {
		fmt.Fprintf(stderr, "hook: %v\n", err)
		return 0
	}
	sel, err := parseEmit(emitValues)
	if err != nil {
		fmt.Fprintf(stderr, "hook: %v\n", err)
		return 0
	}
	content, err := parseContentMode(*contentFlag)
	if err != nil {
		fmt.Fprintf(stderr, "hook: %v\n", err)
		return 0
	}
	if err := validateContentSelection(content, sel); err != nil {
		fmt.Fprintf(stderr, "hook: %v\n", err)
		return 0
	}
	lc, err := hook.ResolveLifecycle(*agentFlag, event)
	if err != nil {
		fmt.Fprintf(stderr, "hook: %v\n", err)
		fs.Usage()
		return 0
	}

	// At most one control response may reach stdout; Kiro's successful response
	// is intentionally empty. committed covers returned partial writes;
	// denyAttempted also covers a writer that panics mid-deny.
	dw := &dirtyWriter{w: stdout}
	denyAttempted := false
	writeFallback := func() {
		if !dw.committed && !denyAttempted {
			writePassthrough(*agentFlag, lc, dw)
		}
	}
	defer func() {
		if r := recover(); r != nil {
			// Retry only while stdout is known clean; never append allow to a deny.
			func() {
				defer func() { _ = recover() }()
				writeFallback()
			}()
			func() {
				defer func() { _ = recover() }()
				if *enforceFlag {
					fmt.Fprintln(stderr, noDecisionMessage)
				} else {
					fmt.Fprintf(stderr, "hook: recovered from panic (%T)\n", r)
				}
			}()
		}
	}()

	// Monitor mode can write its passthrough before observation. Hosts may still
	// wait for the process to exit, but a later panic cannot remove a required
	// response. Kiro intentionally uses an empty success stream.
	if !*enforceFlag {
		writeFallback()
	}

	deny, reason, denyAgent, err := handleHook(event, lc, *agentFlag, sourceAgent, stdin, stderr, hookOptions{
		caseID:           *caseID,
		sel:              sel,
		content:          content,
		includeReasoning: *includeReasoning,
		stateDB:          *stateDB,
		modes:            outputValues,
		file:             *outputFile,
		spool:            *spoolFile,
		httpURL:          *httpURL,
		httpBatch:        *httpBatch,
		httpTO:           *httpTimeout,
		httpAuth:         *httpAuth,
		httpSig:          *httpSigHeader,
		httpTS:           *httpTSHeader,
		insecure:         *httpAllowInsecure,
		gzip:             *httpGzip,
		ruleDirs:         rf.dirs,
		noBuiltin:        rf.noBuiltin,
		enforce:          *enforceFlag,
		visitFlags:       fs,
	})
	if err != nil {
		if *enforceFlag {
			fmt.Fprintln(stderr, noDecisionMessage)
		} else {
			fmt.Fprintf(stderr, "hook: %v\n", err)
		}
	}

	// A clean enforce decision is the only path that attempts a deny. Claim the
	// stream before Write so a panic cannot splice a trailing allow object onto it.
	if *enforceFlag && err == nil && deny && !dw.committed {
		if b, ok := denyBytes(denyAgent, reason); ok {
			denyAttempted = true
			n, werr := dw.Write(b)
			if werr != nil || n != len(b) {
				fmt.Fprintln(stderr, noDecisionMessage)
			}
		} else if hook.DenyUsesExitCode(*agentFlag) {
			denyAttempted = true
			line := []byte(reason + "\n")
			if n, werr := stderr.Write(line); werr == nil && n == len(line) {
				return 2
			}
			// A failed control write cannot communicate a reliable deny. Fall open
			// and let the passthrough response run while stdout is still clean.
			denyAttempted = false
		}
	}
	writeFallback()
	return 0
}

// hookOptions carries the parsed live-handler settings.
type hookOptions struct {
	caseID           string
	sel              emitSelection
	content          contentMode
	includeReasoning bool
	stateDB          string
	modes            []string
	file             string
	spool            string
	httpURL          string
	httpBatch        int
	httpTO           time.Duration
	httpAuth         string
	httpSig          string
	httpTS           string
	insecure         bool
	gzip             bool
	ruleDirs         multiFlag
	noBuiltin        bool
	enforce          bool
	visitFlags       *flag.FlagSet
}

// handleHook maps one payload through the shared pipeline. A deny is returned
// only for a clean match on an agent's enforce-capable pre-tool hook.
func handleHook(event string, lc hook.Lifecycle, agent, sourceAgent string, stdin io.Reader, stderr io.Writer, opts hookOptions) (deny bool, reason, denyAgent string, err error) {
	var httpFlagsSet []string
	if opts.visitFlags != nil {
		opts.visitFlags.Visit(func(f *flag.Flag) {
			if httpOnlyFlags[f.Name] {
				httpFlagsSet = append(httpFlagsSet, f.Name)
			}
		})
	}
	// Hook stdout is reserved for the agent protocol; stdout-mode records use
	// stderr instead.
	sinks, err := parseOutputSinks(opts.modes, outputModeStdout)
	if err != nil {
		return false, "", "", err
	}
	if err := validateEnforceIO(opts.enforce, opts.sel, sinks); err != nil {
		return false, "", "", err
	}
	outputFile, err := expandHookPath(opts.file)
	if err != nil {
		return false, "", "", err
	}
	spoolFile, err := expandHookPath(opts.spool)
	if err != nil {
		return false, "", "", err
	}
	var statePath string
	if sinks.spool {
		statePath, err = hookStatePath(opts.stateDB, spoolFile)
		if err != nil {
			return false, "", "", err
		}
	}
	sink, err := buildSink(sinkConfig{
		modes:         opts.modes,
		defaultMode:   outputModeStdout,
		file:          outputFile,
		spool:         spoolFile,
		httpURL:       opts.httpURL,
		httpBatch:     opts.httpBatch,
		httpTimeout:   opts.httpTO,
		httpAuth:      opts.httpAuth,
		httpSigHeader: opts.httpSig,
		httpTSHeader:  opts.httpTS,
		allowInsecure: opts.insecure,
		gzip:          opts.gzip,
		httpFlagsSet:  httpFlagsSet,
		// A hook fires a fresh process per agent event; records must accumulate
		// into the durable file, not truncate it on each invocation.
		appendFile: true,
	}, stderr)
	if err != nil {
		return false, "", "", err
	}

	run := runID()
	var em *output.Emitter
	if opts.enforce {
		em = output.NewWithSinkAndDiagnostics(sink, run, contentEmitterOptions(opts.content)...)
	} else {
		em = output.NewWithSink(sink, stderr, run, contentEmitterOptions(opts.content)...)
	}
	closeWithDiagnostic := func(err error) error {
		em.Diag("error", err.Error())
		return errors.Join(err, em.Close())
	}

	// A bad body yields a sparse observed event and suppresses enforcement.
	payload, decodeErr := decodeHookPayload(stdin)
	if decodeErr != nil {
		if errors.Is(decodeErr, errOversizedPayload) {
			em.Diag("warn", "hook payload decode: oversized_payload (stdin exceeds limit; failing open)")
		} else {
			em.Diag("warn", fmt.Sprintf("hook payload decode: %v", decodeErr))
		}
	}

	var eng *rule.Engine
	if opts.sel.findings || opts.enforce || len(opts.ruleDirs) > 0 || opts.noBuiltin {
		ruleDirs, expandErr := expandHookRuleDirs(opts.ruleDirs)
		if expandErr != nil {
			return false, "", "", closeWithDiagnostic(expandErr)
		}
		eng, err = buildEngine(ruleDirs, opts.noBuiltin)
		if err != nil {
			return false, "", "", closeWithDiagnostic(err)
		}
	}
	// Hook processes are short-lived, so sequence windows use the shared state
	// database. Unavailable state skips sequence rules; it must not disable an
	// otherwise clean stateless deny.
	var seqStore *sequence.Store
	var stateDB *state.DB
	var stateErr error
	if (opts.sel.findings || opts.enforce) && eng != nil {
		if seqs := eng.SequenceRules(); len(seqs) > 0 {
			if statePath == "" {
				statePath, stateErr = hookStatePath(opts.stateDB, spoolFile)
			}
			if stateErr == nil {
				stateDB, stateErr = state.Open(statePath, 250*time.Millisecond)
			}
			if stateErr != nil {
				em.Diag("warn", fmt.Sprintf("state database unavailable, %d sequence rule(s) skipped for this event: %v", len(seqs), stateErr))
			} else {
				seqStore, stateErr = sequence.NewStore(stateDB.Bolt(), seqs, sequence.DefaultConfig())
				if stateErr != nil {
					em.Diag("warn", fmt.Sprintf("sequence window state unavailable, %d sequence rule(s) skipped for this event: %v", len(seqs), stateErr))
				}
			}
		}
	}
	sequenceUnavailable := stateErr != nil

	events := hook.MapEvents(lc, agent, sourceAgent, hookEventID(run), payload)
	if !opts.includeReasoning {
		filtered := events[:0]
		for _, ev := range events {
			if ev.EventType != model.EventMessageReasoning {
				filtered = append(filtered, ev)
			}
		}
		events = filtered
	}
	responseAgent := agent
	if agent == hook.AgentCopilot && len(events) > 0 && events[0].SourceAgent == hook.AgentVSCode {
		responseAgent = hook.AgentVSCode
	}
	now := time.Now().UTC().Format(time.RFC3339Nano)
	for i := range events {
		if events[i].Timestamp == "" {
			events[i].Timestamp = now
		}
		if events[i].CaseID == "" {
			events[i].CaseID = opts.caseID
		}
	}

	// Enforce-capable pre-action hooks accumulate decision context in both
	// monitor and enforce mode. A malformed payload makes the decision
	// observe-only. Unavailable sequence state still permits a clean stateless
	// match to block, while sequence rules are skipped.
	var dec *pipeline.EnforceDecision
	if hook.EnforceEligible(agent, event, lc) && (opts.sel.findings || opts.enforce) {
		dec = &pipeline.EnforceDecision{ObserveOnly: !opts.enforce || decodeErr != nil}
	}
	var indicators *output.IndicatorAccumulator
	if opts.sel.indicators {
		indicators = output.NewIndicatorAccumulator()
	}
	p := pipeline.New(eng, em, pipeline.Selection{
		Events:     opts.sel.events,
		Findings:   opts.sel.findings,
		Indicators: opts.sel.indicators,
	}, findingOptions(), indicators).WithEnforce(dec)
	if seqStore != nil {
		p.WithSequences(seqStore)
	}
	var processErr error
	for _, ev := range events {
		if err := p.Process(ev, "hook:"+agent); err != nil {
			processErr = errors.Join(processErr, err)
			em.Diag("error", fmt.Sprintf("process hook:%s event %s: %v", agent, ev.EventID, err))
		}
	}
	if opts.sel.indicators {
		for _, ind := range indicators.Materialize() {
			if emitErr := em.EmitIndicator(ind); emitErr != nil {
				em.Diag("error", fmt.Sprintf("emit indicator %s=%s: %v", ind.Type, ind.Value, emitErr))
			}
		}
	}
	// Release the state lock before a potentially slow sink flush.
	if stateDB != nil {
		if closeErr := stateDB.Close(); closeErr != nil {
			em.Diag("warn", fmt.Sprintf("state database close: %v", closeErr))
			stateErr = errors.Join(stateErr, fmt.Errorf("state database close: %w", closeErr))
		}
	}
	// A state error remains fatal unless a clean stateless match already proved
	// a deny. sequenceUnavailable means no sequence observer ran, so any such
	// decision necessarily came from a stateless rule.
	if !(sequenceUnavailable && dec != nil && dec.Blocked) {
		processErr = errors.Join(processErr, stateErr)
	}
	if decision := hookEnforcementDecision(run, opts, dec, processErr, em.Stats().RecordErrors); decision != nil {
		if emitErr := em.EmitEnforcement(*decision); emitErr != nil {
			processErr = errors.Join(processErr, fmt.Errorf("emit enforcement decision %s: %w", decision.DecisionID, emitErr))
		}
	}
	recordErrors := em.Stats().RecordErrors

	// Close the sink before deciding to block: a sink error means the run did not
	// fully succeed, and an uncertain run must fail open (no deny). Only a clean
	// close with a recorded eligible match yields deny. dec.Blocked is itself set
	// by the pipeline only from a trusted matching projection after finding write.
	// Requiring closeErr==nil completes that gate; the only ignored error is an
	// unavailable sequence store when the decision is provably stateless.
	if err := errors.Join(processErr, em.Close()); err != nil {
		return false, "", "", err
	}
	if recordErrors > 0 {
		return false, "", "", fmt.Errorf("output delivery failed: %d record write(s) failed", recordErrors)
	}
	if dec != nil && dec.Blocked {
		return true, dec.Reason, responseAgent, nil
	}
	return false, "", "", nil
}

// hookEnforcementDecision returns Numbat's computed effect for a matched
// pre-action callback. It joins the existing operator record batch before the
// sink closes and before any host control response, so it adds no second
// delivery phase. The record deliberately does not claim response delivery or
// host execution.
func hookEnforcementDecision(run string, opts hookOptions, dec *pipeline.EnforceDecision, processErr error, recordErrors int) *model.EnforcementDecision {
	if dec == nil || !dec.Matched || !opts.sel.findings {
		return nil
	}
	decision := &model.EnforcementDecision{
		SchemaVersion:  model.SchemaVersion,
		DecisionID:     hookDecisionID(run, dec.ActionEventIDs),
		CaseID:         dec.CaseID,
		Timestamp:      time.Now().UTC().Format(time.RFC3339Nano),
		Decision:       model.EnforcementDecisionNoOverride,
		Mode:           model.EnforcementModeMonitor,
		Reason:         model.EnforcementReasonMonitorMode,
		SourceAgent:    dec.SourceAgent,
		SourceType:     dec.SourceType,
		SessionID:      dec.SessionID,
		Model:          dec.Model,
		ModelProvider:  dec.ModelProvider,
		SubAgent:       dec.SubAgent,
		ToolName:       dec.ToolName,
		ToolCallID:     dec.ToolCallID,
		ActionEventIDs: append([]string(nil), dec.ActionEventIDs...),
		FindingIDs:     append([]string(nil), dec.FindingIDs...),
		RuleIDs:        append([]string(nil), dec.RuleIDs...),
	}
	if opts.enforce {
		decision.Mode = model.EnforcementModeEnforce
		switch {
		case processErr != nil || recordErrors > 0 || dec.Tainted || dec.ObserveOnly:
			decision.Reason = model.EnforcementReasonFailOpen
		case dec.Blocked:
			decision.Decision = model.EnforcementDecisionDeny
			decision.Reason = model.EnforcementReasonEnforceRuleMatch
			decision.DenyRuleID = dec.DenyRuleID
			decision.DenyRuleVersion = dec.DenyRuleVersion
		default:
			decision.Reason = model.EnforcementReasonNoEnforceEligibleMatch
		}
	}
	return decision
}

func hookDecisionID(run string, eventIDs []string) string {
	h := sha256.New()
	_, _ = io.WriteString(h, run)
	for _, id := range eventIDs {
		_, _ = io.WriteString(h, "\x00"+id)
	}
	return "enf-" + hex.EncodeToString(h.Sum(nil)[:12])
}

func expandHookPath(path string) (string, error) {
	if path == "" {
		return "", nil
	}
	missing := ""
	path = os.Expand(path, func(key string) string {
		if key == "$" {
			return "$"
		}
		if value, ok := os.LookupEnv(key); ok && value != "" {
			return value
		}
		if key == "HOME" {
			if home, err := os.UserHomeDir(); err == nil && home != "" {
				return home
			}
		}
		if missing == "" {
			missing = key
		}
		return ""
	})
	if missing != "" {
		return "", fmt.Errorf("path references unset environment variable %s", missing)
	}
	if strings.HasPrefix(path, "~/") || strings.HasPrefix(path, `~\`) {
		if home, err := os.UserHomeDir(); err == nil && home != "" {
			return filepath.Join(home, path[2:]), nil
		}
		return "", fmt.Errorf("path uses ~ but the home directory is unavailable")
	}
	return filepath.Clean(path), nil
}

func expandHookRuleDirs(dirs []string) (multiFlag, error) {
	out := make(multiFlag, 0, len(dirs))
	for _, dir := range dirs {
		expanded, err := expandHookPath(dir)
		if err != nil {
			return nil, fmt.Errorf("expand --rules-dir %q: %w", dir, err)
		}
		out = append(out, expanded)
	}
	return out, nil
}

// decodeHookPayload accepts one bounded JSON object and preserves numbers as
// json.Number. A second value or trailing garbage is an error, which suppresses
// enforcement.
func decodeHookPayload(stdin io.Reader) (map[string]any, error) {
	// One byte of headroom distinguishes an exact-cap body from overflow.
	dec := json.NewDecoder(&boundedReader{r: stdin, remaining: maxHookStdin + 1})
	dec.UseNumber()
	var payload map[string]any
	if err := dec.Decode(&payload); err != nil {
		return map[string]any{}, err
	}
	if err := dec.Decode(new(json.RawMessage)); err != io.EOF {
		if err == nil {
			err = fmt.Errorf("unexpected trailing data after JSON payload")
		}
		return map[string]any{}, err
	}
	if payload == nil {
		return map[string]any{}, fmt.Errorf("hook payload must be a JSON object")
	}
	return payload, nil
}

// validateEnforceIO keeps findings off the agent control channel and requires
// an out-of-band sink for the operator's bounded finding stream.
func validateEnforceIO(enforce bool, sel emitSelection, sinks outputSinks) error {
	if !enforce {
		return nil
	}
	if !sel.findings {
		return fmt.Errorf("--enforce requires --emit findings (or --emit all)")
	}
	if sinks.stdout {
		return fmt.Errorf("--enforce does not support --output stdout; use file, spool, and/or http for operator findings")
	}
	return nil
}

// maxHookStdin bounds the hook payload read from stdin. It is the same 4 MiB cap
// the OTLP receiver applies to a POST body (maxOTLPBody): both are untrusted
// inputs that must not exhaust memory, so they share one limit rather than two
// independent magic numbers.
const maxHookStdin = maxOTLPBody

// errOversizedPayload is returned by boundedReader when the stdin payload exceeds
// maxHookStdin. The hook treats it like any other decode failure — an uncertain
// payload that fails open, but logs a distinct oversized_payload diagnostic.
var errOversizedPayload = errors.New("oversized_payload: hook stdin exceeds limit")

// boundedReader reports overflow instead of presenting a truncated body as EOF.
type boundedReader struct {
	r         io.Reader
	remaining int
}

func (b *boundedReader) Read(p []byte) (int, error) {
	if b.remaining <= 0 {
		return 0, errOversizedPayload
	}
	if len(p) > b.remaining {
		p = p[:b.remaining]
	}
	n, err := b.r.Read(p)
	b.remaining -= n
	return n, err
}

// writePassthrough emits the complete control response in one Write. Kiro's
// success contract treats stdout as agent context, so its inert allow response
// is intentionally zero bytes. dirtyWriter tracks whether bytes committed; a
// marshal failure falls back to {}.
func writePassthrough(agent string, lc hook.Lifecycle, stdout io.Writer) {
	if agent == hook.AgentKiro {
		return
	}
	b, err := json.Marshal(hook.PassthroughResponse(agent, lc))
	if err != nil {
		b = []byte("{}")
	}
	b = append(b, '\n')
	_, _ = stdout.Write(b)
}

// dirtyWriter records a returned partial or complete write. A panicking deny
// write is covered separately by denyAttempted, so recovery never appends allow
// to a possibly partial deny.
type dirtyWriter struct {
	w         io.Writer
	committed bool
}

func (d *dirtyWriter) Write(p []byte) (n int, err error) {
	if len(p) == 0 {
		return d.w.Write(p)
	}
	n, err = d.w.Write(p)
	if n > 0 {
		d.committed = true
	}
	return n, err
}

// denyBytes materializes a complete deny response before the single control
// write. Unsupported agents or marshal failures return ok=false and fail open.
func denyBytes(agent, reason string) (b []byte, ok bool) {
	resp, ok := hook.DenyResponse(agent, reason)
	if !ok {
		return nil, false
	}
	b, err := json.Marshal(resp)
	if err != nil {
		return nil, false
	}
	return append(b, '\n'), true
}

// hookEventID builds a stable-shaped, run-correlated event id for a hook event.
func hookEventID(run string) string {
	return "hook-" + run
}

// findingOptions pins one detection time across findings from the same callback.
func findingOptions() finding.Options { return finding.Options{Now: time.Now()} }

// hookStatePath resolves the shared sequence state path and prevents it from
// sharing a bbolt file with the record spool.
func hookStatePath(override, spoolPath string) (string, error) {
	path := override
	if path == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("resolve home for state db: %w", err)
		}
		path = filepath.Join(home, ".numbat", "state.db")
	}
	if spoolPath != "" {
		same, err := sameHookDataPath(spoolPath, path)
		if err != nil {
			return "", fmt.Errorf("compare --spool-file and --state-db: %w", err)
		}
		if same {
			return "", errors.New("--spool-file and --state-db must name different files")
		}
	}
	return path, nil
}

func sameHookDataPath(a, b string) (bool, error) { return sameShipPath(a, b) }

func pathWithResolvedParent(path string) (string, error) {
	path, err := filepath.Abs(filepath.Clean(path))
	if err != nil {
		return "", err
	}
	for {
		resolved, err := filepath.EvalSymlinks(path)
		if err == nil {
			return resolved, nil
		}
		if !errors.Is(err, os.ErrNotExist) {
			return "", err
		}
		info, err := os.Lstat(path)
		if errors.Is(err, os.ErrNotExist) || err == nil && info.Mode()&os.ModeSymlink == 0 {
			break
		}
		if err != nil {
			return "", err
		}
		path, err = resolvedSymlinkTarget(path)
		if err != nil {
			return "", err
		}
	}
	parent := filepath.Dir(path)
	var missing []string
	for {
		resolved, err := filepath.EvalSymlinks(parent)
		if err == nil {
			for i := len(missing) - 1; i >= 0; i-- {
				resolved = filepath.Join(resolved, missing[i])
			}
			return filepath.Join(resolved, filepath.Base(path)), nil
		}
		if !errors.Is(err, os.ErrNotExist) {
			return "", err
		}
		info, lstatErr := os.Lstat(parent)
		if lstatErr == nil && info.Mode()&os.ModeSymlink != 0 {
			target, err := resolvedSymlinkTarget(parent)
			if err != nil {
				return "", err
			}
			for i := len(missing) - 1; i >= 0; i-- {
				target = filepath.Join(target, missing[i])
			}
			return pathWithResolvedParent(filepath.Join(target, filepath.Base(path)))
		}
		if lstatErr != nil && !errors.Is(lstatErr, os.ErrNotExist) {
			return "", lstatErr
		}
		next := filepath.Dir(parent)
		if next == parent {
			return "", err
		}
		missing = append(missing, filepath.Base(parent))
		parent = next
	}
}

func resolvedSymlinkTarget(path string) (string, error) {
	target, err := os.Readlink(path)
	if err != nil {
		return "", err
	}
	if !filepath.IsAbs(target) {
		parent, err := filepath.EvalSymlinks(filepath.Dir(path))
		if err != nil {
			return "", err
		}
		target = filepath.Join(parent, target)
	}
	return filepath.Abs(filepath.Clean(target))
}
