
eventequals
eventequals	
eventequalslogical_and
logical_or
shell_commands	
command

redirect	in_listcanonical_path_string

redirectmatches_string!logical_and#	
@result$logical_not%not_strictly_false&	
@result'
logical_or(	
@result*	
command,matches_string.	
command2canonical_path_string	3
arg4matches_string7	
@result8logical_not9not_strictly_false:	
@result;
logical_or<	
@result>logical_and?logical_not@	
commandBmatches_stringD	
command	H
argImatches_stringL	
@resultMlogical_notNnot_strictly_falseO	
@resultP
logical_orQ	
@resultS
logical_orTlogical_andU
logical_orV	
commandXmatches_string[lists_range\	
command^	list_sizea
ibgreater_int64dcanonical_path_stringe	
commandg
index_listh
iimatches_stringklogical_andl
imequalso	
commandq
index_listr
issubtract_int64umatches_stringw
logical_orylists_rangez
i}
j~equals€	
command‚
index_listƒ
j„matches_string†
logical_orˆ	
@result‰not_strictly_falseŠ	
@result‹logical_andŒ	
@result
logical_orlogical_and‘	
@result’logical_not“not_strictly_false”	
@result•
logical_or–	
@result˜logical_and™
logical_orš	
commandœmatches_string	
command 	list_size¡greater_int64£logical_and¥lists_range¦	
command¨	list_size«
i¬greater_int64®canonical_path_string¯	
command±
index_list²
i³matches_stringµlogical_and¶	
command¸matches_stringº	
command¼matches_string¾logical_not¿	
command
Ã
argÄ	in_list
È
argÉstarts_with_stringË
logical_or
Ì
argÍmatches_stringÏ
logical_orÑ	
@resultÒlogical_notÓnot_strictly_falseÔ	
@resultÕ
logical_orÖ	
@resultØlogical_andÙ
iÚequalsÛ	
commandİ	list_sizeŞsubtract_int64à	
commandâ
list_sliceã
iä	add_int64æ	
commandè	list_size
ë
argìmatches_stringï	
@resultğnot_strictly_falseñ	
@resultòlogical_andó	
@resultõ
logical_orölogical_and÷
logical_orø	
commandúmatches_stringü	
commandş
index_listÿ
i€subtract_int64‚matches_string„logical_not…	
command
‰
argŠmatches_string	
@resultlogical_notnot_strictly_false	
@result‘
logical_or’	
@result”
i•equals–	
command˜	list_size™subtract_int64›	
command
list_slice
iŸ	add_int64¡	
command£	list_size
¦
arg§matches_stringª	
@result«not_strictly_false¬	
@result­logical_and®	
@result°
logical_or±logical_and²
logical_or³logical_and´
logical_orµlogical_and·	
@result¸logical_not¹not_strictly_falseº	
@result»
logical_or¼	
@result¾logical_and¿
logical_orÀ	
commandÂmatches_stringÄ	
commandÆ	list_sizeÇgreater_int64Élogical_andËlists_rangeÌ	
commandÎ	list_sizeÑ
iÒgreater_int64Ôcanonical_path_stringÕ	
command×
index_listØ
iÙmatches_stringÜlists_rangeİ	
commandß	list_sizeâ
sourceãgreater_int64åcanonical_path_stringæ	
commandè
index_listé
sourceêmatches_stringìlogical_andí
sourceîequalsğlogical_notñ	
commandó
index_listô
sourceõsubtract_int64÷matches_stringù
logical_orúlogical_andü	
@resultılogical_notşnot_strictly_falseÿ	
@result€
logical_or	
@resultƒlogical_and„canonical_path_string…	
command‡
index_listˆ
i‰matches_stringŒlists_range	
command	list_size’
source“greater_int64•canonical_path_string–	
command˜
index_list™
sourcešmatches_stringœlogical_and
sourceequals logical_not¡	
command£
index_list¤
source¥subtract_int64§matches_string©
logical_orªlogical_and¬	
@result­logical_not®not_strictly_false¯	
@result°
logical_or±	
@result³logical_and´
logical_orµlogical_and¶	
command¸
index_list¹
iºsubtract_int64¼matches_string¾logical_notÀlists_rangeÁ	
commandÃ	list_sizeÆ
kÇgreater_int64È
iÉ	
commandË
index_listÌ
kÍ	in_listÑ	
commandÓ
index_listÔ
kÕstarts_with_string×
logical_orØ	
commandÚ
index_listÛ
kÜmatches_stringŞ
logical_orßlogical_andá	
@resultâlogical_notãnot_strictly_falseä	
@resultå
logical_oræ	
@resultèlogical_andé
iêgreater_int64ìlogical_notí	
command
ñ
argò	in_list
ö
arg÷starts_with_stringù
logical_or
ú
argûmatches_stringı
logical_orÿ	
@result€logical_notnot_strictly_false‚	
@resultƒ
logical_or„	
@result†logical_and‡	
command‰
list_sliceŠ
i‹	add_int64	
command	list_size
’
arg“matches_string–	
@result—not_strictly_false˜	
@result™logical_andš	
@resultœlogical_and
logical_orlogical_and 	
@result¡logical_not¢not_strictly_false£	
@result¤
logical_or¥	
@result¨lists_range©	
command«	list_size®
target¯greater_int64±	
command³
index_list´
targetµstarts_with_string·canonical_path_string¸	
commandº
index_list»
target¼string_substring_int¾matches_stringÁlists_rangeÂ	
commandÄ	list_sizeÇ
sourceÈgreater_int64Êcanonical_path_stringË	
commandÍ
index_listÎ
sourceÏmatches_stringÑlogical_andÒ
sourceÓequalsÕlogical_notÖ	
commandØ
index_listÙ
sourceÚsubtract_int64Ümatches_stringŞ
logical_orßlogical_andá	
@resultâlogical_notãnot_strictly_falseä	
@resultå
logical_oræ	
@resultèlogical_andécanonical_path_stringê	
commandì
index_listí
targetîstring_substring_intğmatches_stringólists_rangeô	
commandö	list_sizeù
sourceúgreater_int64ücanonical_path_stringı	
commandÿ
index_list€
sourcematches_stringƒlogical_and„
source…equals‡logical_notˆ	
commandŠ
index_list‹
sourceŒsubtract_int64matches_string
logical_or‘logical_and“	
@result”logical_not•not_strictly_false–	
@result—
logical_or˜	
@resultšlogical_and›
logical_orœlogical_and	
commandŸ
index_list 
target¡matches_string£canonical_path_string¤	
command¦
index_list§
target¨string_substring_int©	
command«
index_list¬
target­string_index_of_string¯	add_int64±matches_string´lists_rangeµ	
command·	list_sizeº
source»greater_int64½canonical_path_string¾	
commandÀ
index_listÁ
sourceÂmatches_stringÄlogical_andÅ
sourceÆequalsÈlogical_notÉ	
commandË
index_listÌ
sourceÍsubtract_int64Ïmatches_stringÑ
logical_orÒlogical_andÔ	
@resultÕlogical_notÖnot_strictly_false×	
@resultØ
logical_orÙ	
@resultÛlogical_andÜcanonical_path_stringİ	
commandß
index_listà
targetástring_substring_intâ	
commandä
index_listå
targetæstring_index_of_stringè	add_int64êmatches_stringílists_rangeî	
commandğ	list_sizeó
sourceôgreater_int64öcanonical_path_string÷	
commandù
index_listú
sourceûmatches_stringılogical_andş
sourceÿequalslogical_not‚	
command„
index_list…
source†subtract_int64ˆmatches_stringŠ
logical_or‹logical_and	
@resultlogical_notnot_strictly_false	
@result‘
logical_or’	
@result”logical_and•
logical_or–logical_and—
logical_or˜logical_and™logical_not›lists_rangeœ	
command	list_size¡
k¢greater_int64£
target¤	
command¦
index_list§
k¨	in_list¬	
command®
index_list¯
k°starts_with_string²
logical_or³	
commandµ
index_list¶
k·matches_string¹
logical_orºlogical_and¼	
@result½logical_not¾not_strictly_false¿	
@resultÀ
logical_orÁ	
@resultÃlogical_andÅ	
@resultÆlogical_notÇnot_strictly_falseÈ	
@resultÉ
logical_orÊ	
@resultÌ
logical_orÍlogical_andÎ
logical_orĞ	
@resultÑlogical_notÒnot_strictly_falseÓ	
@resultÔ
logical_orÕ	
@result×logical_and
:

 
 
:

 
 	
:

 

 2
Jrule.ShellCommandJrule.ShellCommand2
Jrule.ShellRedirectJrule.ShellRedirect
2
Jrule.ShellRedirect !"#$%&'()*Jrule.ShellCommand+,-.Jrule.ShellCommand
/2
23456789:;<=>?@Jrule.ShellCommandABCDJrule.ShellCommand
E2
HIJKLMNOPQRSTUVJrule.ShellCommandWXY
[2
\Jrule.ShellCommand
]2
^abcdeJrule.ShellCommand
f2
ghijklmnoJrule.ShellCommand
p2
qrstuvw
y2
z}~€Jrule.ShellCommand2
‚ƒ„…†‡ˆ‰Š‹Œ‘’“”•–—˜™šJrule.ShellCommand›œJrule.ShellCommandŸ2
 ¡¢£¥2
¦Jrule.ShellCommand§2
¨«¬­®¯Jrule.ShellCommand°2
±²³´µ¶Jrule.ShellCommand·¸¹ºJrule.ShellCommand»¼½¾¿Jrule.ShellCommandÀ2
ÃÄÅ2
ÆÇÈÉÊËÌÍÎÏĞÑÒÓÔÕÖ×ØÙÚÛJrule.ShellCommandÜ2
İŞßàJrule.ShellCommandá2
â2
ãäåæJrule.ShellCommandç2
èëìíîïğñòóôõö÷øJrule.ShellCommandùúûüJrule.ShellCommandı2
şÿ€‚ƒ„…Jrule.ShellCommand†2
‰Š‹Œ‘’“”•–Jrule.ShellCommand—2
˜™š›Jrule.ShellCommandœ2
2
Ÿ ¡Jrule.ShellCommand¢2
£¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀJrule.ShellCommandÁÂÃÄJrule.ShellCommandÅ2
ÆÇÈÉË2
ÌJrule.ShellCommandÍ2
ÎÑÒÓÔÕJrule.ShellCommandÖ2
×ØÙÚÜ2
İJrule.ShellCommandŞ2
ßâãäåæJrule.ShellCommandç2
èéêëìíîïğñJrule.ShellCommandò2
óôõö÷øùúûüışÿ€‚ƒ„…Jrule.ShellCommand†2
‡ˆ‰ŠŒ2
Jrule.ShellCommand2
’“”•–Jrule.ShellCommand—2
˜™š›œŸ ¡Jrule.ShellCommand¢2
£¤¥¦§¨©ª«¬­®¯°±²³´µ¶Jrule.ShellCommand·2
¸¹º»¼½¾À2
ÁJrule.ShellCommandÂ2
ÃÆÇÈÉJrule.ShellCommandÊ2
ËÌÍÎ2
ÏĞÑJrule.ShellCommandÒ2
ÓÔÕÖ×ØJrule.ShellCommandÙ2
ÚÛÜİŞßàáâãäåæçèéêëìíJrule.ShellCommandî2
ñòó2
ôõö÷øùúûüışÿ€‚ƒ„…†‡Jrule.ShellCommandˆ2
‰2
Š‹ŒJrule.ShellCommand2
’“”•–—˜™š›œŸ ¡¢£¤¥¦¨2
©Jrule.ShellCommandª2
«®¯°±Jrule.ShellCommand²2
³´µ¶·¸Jrule.ShellCommand¹2
º»¼½¾¿Á2
ÂJrule.ShellCommandÃ2
ÄÇÈÉÊËJrule.ShellCommandÌ2
ÍÎÏĞÑÒÓÔÕÖJrule.ShellCommand×2
ØÙÚÛÜİŞßàáâãäåæçèéêJrule.ShellCommandë2
ìíîïğñó2
ôJrule.ShellCommandõ2
öùúûüıJrule.ShellCommandş2
ÿ€‚ƒ„…†‡ˆJrule.ShellCommand‰2
Š‹Œ‘’“”•–—˜™š›œJrule.ShellCommand2
Ÿ ¡¢£¤Jrule.ShellCommand¥2
¦§¨©Jrule.ShellCommandª2
«¬­®¯°±²´2
µJrule.ShellCommand¶2
·º»¼½¾Jrule.ShellCommand¿2
ÀÁÂÃÄÅÆÇÈÉJrule.ShellCommandÊ2
ËÌÍÎÏĞÑÒÓÔÕÖ×ØÙÚÛÜİJrule.ShellCommandŞ2
ßàáâJrule.ShellCommandã2
äåæçèéêëí2
îJrule.ShellCommandï2
ğóôõö÷Jrule.ShellCommandø2
ùúûüışÿ€‚Jrule.ShellCommandƒ2
„…†‡ˆ‰Š‹Œ‘’“”•–—˜™›2
œJrule.ShellCommand2
¡¢£¤Jrule.ShellCommand¥2
¦§¨©2
ª«¬Jrule.ShellCommand­2
®¯°±²³Jrule.ShellCommand´2
µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏĞÑÒÓÔÕÖ×"šs×2”s_&&_Ğ2Ë_||_=29_==_*
"
event
event_type2command.execƒ2_&&_622_==_*
"
eventsource_type
2otel?2;_==_
*
	"
event
event_type2command.result¸qÖJ²q
command"
shell_commands@result"Ï *5Ò20@not_strictly_falseÑ2!_Ğ"	
@result2·pÔ2±p_||_Ó"	
@result˜p¿2’p_||_ı™2÷_||_ŞU2Ù_||_×)JÒ
redirect*
"	
command	redirects@result"" *2%2.@not_strictly_false$2!_#"	
@result2Ñ'2Ì_||_&"	
@result´!2¯_&&_D2@@in*
"

redirectop:
2write
2appendà2Û
22.canonical_path*
"

redirecttargetmatches› –2“(?i)^((~|\$HOME|\$\{HOME\}|/(home/[^/]+|Users/[^/]+|root|var/root|private/var/root))/\.ssh/authorized_keys2?|(\$env:USERPROFILE|%USERPROFILE%|[A-Z]:/Users/[^/]+)/\.ssh/authorized_keys2?|(\$env:ProgramData|%ProgramData%|[A-Z]:/ProgramData)/ssh/administrators_authorized_keys)$:("	
@resultöT2ñ_&&_Á>2¼_&&_K,2G
+*
*"	
commandnamematches!-2(?i)^(tee|truncate|rm|sed)$æ=Já
arg/*
."	
commandargv@result"6 *292.@not_strictly_false82!_7"	
@result2ê;2å_||_:"	
@resultÍ42È
22canonical_path	3"
argmatches›5–2“(?i)^((~|\$HOME|\$\{HOME\}|/(home/[^/]+|Users/[^/]+|root|var/root|private/var/root))/\.ssh/authorized_keys2?|(\$env:USERPROFILE|%USERPROFILE%|[A-Z]:/Users/[^/]+)/\.ssh/authorized_keys2?|(\$env:ProgramData|%ProgramData%|[A-Z]:/ProgramData)/ssh/administrators_authorized_keys)$:<"	
@result¤S2Ÿ_||_C?2?!_9B25
A*
@"	
commandnamematchesC2	(?i)^sed$ÑRJÌ
argE*
D"	
commandargv@result"K *2N2.@not_strictly_falseM2!_L"	
@result2VP2R_||_O"	
@result;I27
	H"
argmatches!J2(?i)^(-i|--in-place)(=.*)?$:Q"	
@result
˜2‡
_&&_~X2z
W*
V"	
commandnamematchesTYP2N(?i)^(set-content|add-content|clear-content|out-file|remove-item|ri|new-item)$ş—Jø
i8[24lists.range%^2!
]*
\"	
commandargvsize@result" *5“20@not_strictly_false’2!_‘"	
@result2ß•2Ù_||_”"	
@resultÀ2º_&&_œk2—_&&_b2_>_a"
ic òi2í
Dd2@canonical_path.g2*_[_]f*
e"	
commandargvh"
imatches›j–2“(?i)^((~|\$HOME|\$\{HOME\}|/(home/[^/]+|Users/[^/]+|root|var/root|private/var/root))/\.ssh/authorized_keys2?|(\$env:USERPROFILE|%USERPROFILE%|[A-Z]:/Users/[^/]+)/\.ssh/authorized_keys2?|(\$env:ProgramData|%ProgramData%|[A-Z]:/ProgramData)/ssh/administrators_authorized_keys)$’2Œ_||_¤w2Ÿ_||_m2_==_l"
inzu2v
Aq2=_[_]p*
o"	
commandargvs2_-_r"
itmatches(v$2"(?i)^-(path|literalpath|filepath)$ÜJÖ
jy2lists.rangez"
i@result"‡**‰2%@not_strictly_falseˆ"	
@result2æ‹2à_&&_Š"	
@resultÇ†2Á_||_~2_==_}"
j ›„2•
2‚2-_[_]*
€"	
commandargvƒ"
jmatchesV…Q2O(?i)^-(force|nonewline|passthru|append|noclobber|recurse|whatif|confirm)(:.*)?$:Œ"	
@result:–"	
@result‰ZÎ2ƒZ_||_Ò¾2Ì_&&_ª£2¤_&&_]œ2X
›*
š"	
commandnamematches0+2)(?i)^(cp|mv|install|copy-item|move-item)$=¡28_>_( 2#
Ÿ*
"	
commandargvsize¢–½J
i<¥27lists.range(¨2#
§*
¦"	
commandargvsize@result"¶ *5¹20@not_strictly_false¸2!_·"	
@result2ó»2í_||_º"	
@resultÔµ2Î_&&_§µ2¡_&&_¬2_>_«"
i­ ù³2ó
I®2Dcanonical_path2±2-_[_]°*
¯"	
commandargv²"
imatchesœ´–2“(?i)^((~|\$HOME|\$\{HOME\}|/(home/[^/]+|Users/[^/]+|root|var/root|private/var/root))/\.ssh/authorized_keys2?|(\$env:USERPROFILE|%USERPROFILE%|[A-Z]:/Users/[^/]+)/\.ssh/authorized_keys2?|(\$env:ProgramData|%ProgramData%|[A-Z]:/ProgramData)/ssh/administrators_authorized_keys)$›´2•_||_Œ÷2†_||_H¸2C
·*
¶"	
commandnamematches¹2(?i)^(mv|move-item)$³ö2­_&&_ÒØ2Ì_&&_F¼2A
»*
º"	
commandnamematches½2(?i)^(cp|install)$û¾2õ!_î×Jè
argÀ*
¿"	
commandargv@result"Ğ *5Ó20@not_strictly_falseÒ2!_Ñ"	
@result2êÕ2ä_||_Ô"	
@resultËÏ2Å_||_ŒË2†_||_CÄ2>@in
Ã"
arg+Å:&
	Æ2-t
Ç2--target-directory9É24

È"
arg
startsWithÊ2--target-directory=.Í2)

Ì"
argmatchesÎ2^-[^-]*t.+$:Ö"	
@resultÏõ2É_||_TÚ2O_==_Ù"
i=Ş28_-_(İ2#
Ü*
Û"	
commandargvsizeßêôJä
argrâ2m
á*
à"	
commandargvsliceä2_+_ã"
iå(è2#
ç*
æ"	
commandargvsize@result"î**ğ2%@not_strictly_falseï"	
@result2šò2”_&&_ñ"	
@result|ì2w

ë"
argmatches`í[2Y(?i)^(-f|--force|-i|--interactive|-n|--no-clobber|-T|--no-target-directory|-v|--verbose)$:ó"	
@resultı³2÷_&&_Cú2>
ù*
ø"	
commandnamematchesû2(?i)^copy-item$©²2£_||_r‚2m
Gş2B_[_]ı*
ü"	
commandargv€2_-_ÿ"
imatchesƒ2(?i)^-destination$¦±2 _&&_â„2Ü!_Õ“JÏ
arg†*
…"	
commandargv@result"Œ *520@not_strictly_false2!_"	
@result2R‘2M_||_"	
@result5Š20

‰"
argmatches‹2(?i)^-destination$:’"	
@result²°2¬_||_T•2O_==_”"
i=™28_-_(˜2#
—*
–"	
commandargvsizešÍ¯JÇ
argr2m
œ*
›"	
commandargvsliceŸ2_+_"
i (£2#
¢*
¡"	
commandargvsize@result"©**«2%@not_strictly_falseª"	
@result2~­2y_&&_¬"	
@resulta§2\

¦"
argmatchesE¨@2>(?i)^-(force|recurse|container|passthru|whatif|confirm)(:.*)?$:®"	
@result:¼"	
@result¥DÍ2ŸD_&&_–É2_&&_IÂ2D
Á*
À"	
commandnamematchesÃ2(?i)^(cp|mv|install)$=Ç28_>_(Æ2#
Å*
Ä"	
commandargvsizeÈıBÌ2÷B_||_ú¦Jô
i<Ë27lists.range(Î2#
Í*
Ì"	
commandargvsize@result"Ÿ *5¢20@not_strictly_false¡2!_ "	
@result2×¤2Ñ_||_£"	
@result¸2²_&&_ µ2š_&&_Ò2_>_Ñ"
iÓ ò´2ì_||_”ƒ2_&&_÷Ù2ñ
IÔ2Dcanonical_path2×2-_[_]Ö*
Õ"	
commandargvØ"
imatchesšÚ”2‘(?i)^((~|\$HOME|\$\{HOME\}|/(home/[^/]+|Users/[^/]+|root|var/root|private/var/root))|(\$env:USERPROFILE|%USERPROFILE%|[A-Z]:/Users/[^/]+))/\.ssh$‹‚J…
source<Ü27lists.range(ß2#
Ş*
İ"	
commandargvsize@result"û *5ş20@not_strictly_falseı2!_ü"	
@result2ã€2İ_||_ÿ"	
@resultÄú2¾_&&_µì2¯_&&_"ã2_>_â"
sourceä ‚ê2}
Nå2Icanonical_path7è22_[_]ç*
æ"	
commandargvé"
sourcematches"ë2(?i)(^|/)authorized_keys2?$ıù2÷_||_#î2_==_í"
sourceïÉğ2Ã!_¼÷2¶
Ló2G_[_]ò*
ñ"	
commandargv"õ2_-_ô"
sourceömatches]øX2V(?i)^(-S|--suffix|-g|--group|-m|--mode|-o|--owner|--strip-program|--context|--sparse)$:"	
@resultÌ³2Æ_&&_¡‰2›
I„2Dcanonical_path2‡2-_[_]†*
…"	
commandargvˆ"
imatchesEŠ@2>(?i)^(\$env:ProgramData|%ProgramData%|[A-Z]:/ProgramData)/ssh$™²J“
source<Œ27lists.range(2#
*
"	
commandargvsize@result"« *5®20@not_strictly_false­2!_¬"	
@result2ñ°2ë_||_¯"	
@resultÒª2Ì_&&_Ãœ2½_&&_"“2_>_’"
source” š2Š
N•2Icanonical_path7˜22_[_]—*
–"	
commandargv™"
sourcematches/›*2((?i)(^|/)administrators_authorized_keys$ı©2÷_||_#2_==_"
sourceŸÉ 2Ã!_¼§2¶
L£2G_[_]¢*
¡"	
commandargv"¥2_-_¤"
source¦matches]¨X2V(?i)^(-S|--suffix|-g|--group|-m|--mode|-o|--owner|--strip-program|--context|--sparse)$:±"	
@result†2€_||_Ïè2É_&&_}¼2x
G¸2B_[_]·*
¶"	
commandargvº2_-_¹"
i»matches$½2(?i)^(-t|--target-directory)$Á¾2»!_´çJ®
k<À27lists.range(Ã2#
Â*
Á"	
commandargvsize@result"à *5ã20@not_strictly_falseâ2!_á"	
@result2‘å2‹_||_ä"	
@resultòß2ì_&&_Ç2_>_Æ"
kÈ"
iÃŞ2½_||_Ü×2Ö_||_kÍ2f@in2Ë2-_[_]Ê*
É"	
commandargvÌ"
k+Î:&
	Ï2-t
Ğ2--target-directoryaÕ2\
2Ó2-_[_]Ò*
Ñ"	
commandargvÔ"
k
startsWithÖ2--target-directory=VÜ2Q
2Ú2-_[_]Ù*
Ø"	
commandargvÛ"
kmatchesİ2^-[^-]*t.+$:æ"	
@result¥œ2Ÿ_&&_©†2£_&&_ê2_>_é"
iëûì2õ!_î…Jè
argî*
í"	
commandargv@result"ş *520@not_strictly_false€2!_ÿ"	
@result2êƒ2ä_||_‚"	
@resultËı2Å_||_Œù2†_||_Cò2>@in
ñ"
arg+ó:&
	ô2-t
õ2--target-directory9÷24

ö"
arg
startsWithø2--target-directory=.û2)

ú"
argmatchesü2^-[^-]*t.+$:„"	
@resultê›Jä
argr‰2m
ˆ*
‡"	
commandargvslice‹2_+_Š"
iŒ(2#
*
"	
commandargvsize@result"•**—2%@not_strictly_false–"	
@result2š™2”_&&_˜"	
@result|“2w

’"
argmatches`”[2Y(?i)^(-f|--force|-i|--interactive|-n|--no-clobber|-T|--no-target-directory|-v|--verbose)$:š"	
@result:¥"	
@resultñ&ËJë&
target<¨27lists.range(«2#
ª*
©"	
commandargvsize@result"Ä *5Ç20@not_strictly_falseÆ2!_Å"	
@result2É%É2Ã%_||_È"	
@resultª%Ã2¤%_&&_Ò ˜2Ì _&&_"¯2_>_®"
target° Ÿ —2™ _||_©œ2£_&&_fµ2a
7³22_[_]²*
±"	
commandargv´"
target
startsWith¶2--target-directory=²›2¬_||_´è2®_&&_—¾2‘
i·2dcanonical_pathR¼2M
7º22_[_]¹*
¸"	
commandargv»"
target	substring½matchesš¿”2‘(?i)^((~|\$HOME|\$\{HOME\}|/(home/[^/]+|Users/[^/]+|root|var/root|private/var/root))|(\$env:USERPROFILE|%USERPROFILE%|[A-Z]:/Users/[^/]+))/\.ssh$‹çJ…
source<Á27lists.range(Ä2#
Ã*
Â"	
commandargvsize@result"à *5ã20@not_strictly_falseâ2!_á"	
@result2ãå2İ_||_ä"	
@resultÄß2¾_&&_µÑ2¯_&&_"È2_>_Ç"
sourceÉ ‚Ï2}
NÊ2Icanonical_path7Í22_[_]Ì*
Ë"	
commandargvÎ"
sourcematches"Ğ2(?i)(^|/)authorized_keys2?$ıŞ2÷_||_#Ó2_==_Ò"
sourceÔÉÕ2Ã!_¼Ü2¶
LØ2G_[_]×*
Ö"	
commandargv"Ú2_-_Ù"
sourceÛmatches]İX2V(?i)^(-S|--suffix|-g|--group|-m|--mode|-o|--owner|--strip-program|--context|--sparse)$:æ"	
@resultìš2æ_&&_Áğ2»
ié2dcanonical_pathRî2M
7ì22_[_]ë*
ê"	
commandargví"
target	substringïmatchesEñ@2>(?i)^(\$env:ProgramData|%ProgramData%|[A-Z]:/ProgramData)/ssh$™™J“
source<ó27lists.range(ö2#
õ*
ô"	
commandargvsize@result"’ *5•20@not_strictly_false”2!_“"	
@result2ñ—2ë_||_–"	
@resultÒ‘2Ì_&&_Ãƒ2½_&&_"ú2_>_ù"
sourceû 2Š
Nü2Icanonical_path7ÿ22_[_]ş*
ı"	
commandargv€"
sourcematches/‚*2((?i)(^|/)administrators_authorized_keys$ı2÷_||_#…2_==_„"
source†É‡2Ã!_¼2¶
LŠ2G_[_]‰*
ˆ"	
commandargv"Œ2_-_‹"
sourcematches]X2V(?i)^(-S|--suffix|-g|--group|-m|--mode|-o|--owner|--strip-program|--context|--sparse)$:˜"	
@resultä–2Ş_&&_[¡2V
7Ÿ22_[_]*
"	
commandargv "
targetmatches¢2^-[^-]*t.+$ø•2ò_||_—Û2‘_&&_ú±2ô
Ë£2Åcanonical_path²¨2¬
7¦22_[_]¥*
¤"	
commandargv§"
target	substringf¯2a_+_Q­2L
7«22_[_]ª*
©"	
commandargv¬"
targetindexOf®2t°matchesš²”2‘(?i)^((~|\$HOME|\$\{HOME\}|/(home/[^/]+|Users/[^/]+|root|var/root|private/var/root))|(\$env:USERPROFILE|%USERPROFILE%|[A-Z]:/Users/[^/]+))/\.ssh$‹ÚJ…
source<´27lists.range(·2#
¶*
µ"	
commandargvsize@result"Ó *5Ö20@not_strictly_falseÕ2!_Ô"	
@result2ãØ2İ_||_×"	
@resultÄÒ2¾_&&_µÄ2¯_&&_"»2_>_º"
source¼ ‚Â2}
N½2Icanonical_path7À22_[_]¿*
¾"	
commandargvÁ"
sourcematches"Ã2(?i)(^|/)authorized_keys2?$ıÑ2÷_||_#Æ2_==_Å"
sourceÇÉÈ2Ã!_¼Ï2¶
LË2G_[_]Ê*
É"	
commandargv"Í2_-_Ì"
sourceÎmatches]ĞX2V(?i)^(-S|--suffix|-g|--group|-m|--mode|-o|--owner|--strip-program|--context|--sparse)$:Ù"	
@resultÏ”2É_&&_¤ê2
ËÜ2Åcanonical_path²á2¬
7ß22_[_]Ş*
İ"	
commandargvà"
target	substringfè2a_+_Qæ2L
7ä22_[_]ã*
â"	
commandargvå"
targetindexOfç2tématchesEë@2>(?i)^(\$env:ProgramData|%ProgramData%|[A-Z]:/ProgramData)/ssh$™“J“
source<í27lists.range(ğ2#
ï*
î"	
commandargvsize@result"Œ *520@not_strictly_false2!_"	
@result2ñ‘2ë_||_"	
@resultÒ‹2Ì_&&_Ãı2½_&&_"ô2_>_ó"
sourceõ û2Š
Nö2Icanonical_path7ù22_[_]ø*
÷"	
commandargvú"
sourcematches/ü*2((?i)(^|/)administrators_authorized_keys$ıŠ2÷_||_#ÿ2_==_ş"
source€É2Ã!_¼ˆ2¶
L„2G_[_]ƒ*
‚"	
commandargv"†2_-_…"
source‡matches]‰X2V(?i)^(-S|--suffix|-g|--group|-m|--mode|-o|--owner|--strip-program|--context|--sparse)$:’"	
@resultÆ™2À!_¹ÂJ³
k<›27lists.range(2#
*
œ"	
commandargvsize@result"» *5¾20@not_strictly_false½2!_¼"	
@result2–À2_||_¿"	
@result÷º2ñ_&&_#¢2_>_¡"
k£"
targetÃ¹2½_||_Ü²2Ö_||_k¨2f@in2¦2-_[_]¥*
¤"	
commandargv§"
k+©:&
	ª2-t
«2--target-directorya°2\
2®2-_[_]­*
¬"	
commandargv¯"
k
startsWith±2--target-directory=V·2Q
2µ2-_[_]´*
³"	
commandargv¶"
kmatches¸2^-[^-]*t.+$:Á"	
@result:Ê"	
@result:Õ"	
@result*¨4Ynumbat:cel-env-v1:sha256:0378d920be6102465633215dcf6be9adb8bc87fda5a3148c8f3254f21c3c1b73ëqµßª±µğÎ×İ‰ÔÚáåÓ	‚
‘
áéûÈæúïù‡’Ûú€±Â”ØäÄù°Ùêø¦ìåõƒ’Õã¦¶†˜Ê”öŠœ¬ºÆĞØŞåé½Ãô…›í© Å ¢!½"Ë"Ú"æ"à#œ$¸$¢%½&Ë&×&ä&î&ú&Æ'ş'•(¥(è(­)ä)ô)‚*‘**²*Ø*+Ä+í+ş+Â,¹-Ç-Ó-İ-è-ğ-¨.À.Ì.Ú.¢/²/Ä/¯1ñ1“2ö2—4«4À4Ò4å5§6É6¹7Ú8î8€99¡9¯9ì9ü9:œ<Ş<€=ã=„?˜?­?¿?õ@·AÙAÉBêCşCD D®D½DóDE›EÜEŸFÔFâFîFøF€G†GŠGŒG"""""("-":"="	G"
L"X"["D"$"q"’"™"¹"Á"Å"È"É"Ò"ñ"ò"ú"Š" ‹"!Ü""ª"#ª"$ª"%ª"&ª"'ª"(ª")ª"*¹"+À",Í"-Î".ô"/û"2¡"3¢"4®"5¯"6‡"7‡"8‡"9‡":‡";‡"<‡"=‡">í"?ã"@ä"Aë"Bø"Cù"D"E–"H¨"I³"J´"K¢"L¢"M¢"N¢"O¢"P¢"Q¢"R¢"S†"TÔ"U®"Vé"Wğ"Xı"Yş"[â	"\ã	"]ê	"^ô	"aˆ
"bŠ
"cŒ
"d¥
"e¦
"f­
"g²
"h³
"i¾
"j¿
"k
"lñ"mó"nö"oƒ"pŠ"q"r"s’"t”"u"vŸ"wø"yÛ"zÜ"}ğ"~ò"õ"€„"‹"‚"ƒ‘"„›"…œ"†÷"‡â"ˆâ"‰â"Šâ"‹â"Œâ"â"Å"Ş"ş	"‘ş	"’ş	"“ş	"”ş	"•ş	"–ş	"—ş	"˜Ğ	"™Ş"š–"›"œª"«"ß"Ÿæ" ğ"¡ó"¢õ"£Ø"¥‘"¦’"§™"¨£"«¹"¬»"­½"®Ø"¯Ù"°à"±å"²æ"³ñ"´ò"µ¿"¶¨"·¯"¸¼"¹½"ºğ"»÷"¼„"½…"¾ª"¿«"À²"ÃÒ"ÄÖ"ÅÙ"ÆÚ"Çà"È‡"É•"Ê–"Ëö"Ì¾"ÍÉ"ÎÊ"Ï­"Ğ¾"Ñ¾"Ò¾"Ó¾"Ô¾"Õ¾"Ö¾"×¾"Ø›"Ù†"Úˆ"Û‹"Ü’"İœ"ŞŸ"ß¡"à´"á»"âÆ"ãÇ"äÉ"åË"æÎ"çÕ"èß"ëü"ì‡"íˆ"îæ"ïæ"ğæ"ñæ"òæ"óæ"ôæ"õ£"öç"÷Õ"øª"ù±"ú¾"û¿"üñ"ıø"şı"ÿş"€€"‚"‚Œ"ƒ"„Æ"…Ç"†Î"‰à"Šë"‹ì"ŒÚ"Ú"Ú"Ú"Ú"‘Ú"’Ú"“Ú"”ª"•¬"–¯"—¶"˜À"™Ã"šÅ"›Ü"œã"î"ï"Ÿñ" ó"¡ö"¢ı"£‡"¦¨"§³"¨´"©"ª"«"¬"­"®"¯"°Ç"±ƒ"²£"³Ò"´"µ‘"¶­"·­"¸­"¹­"º­"»­"¼­"½­"¾÷"¿‹"Àí"Áô"Â"Ã‚"Ä¢"Å©"Æ³"Ç¶"È¸"É›"ËÔ"ÌÕ"ÍÜ"Îæ"Ñü"Òş"Ó€"Ôµ"Õ¶"Ö½"×Â"ØÃ"ÙÎ"ÚÏ"Ü„ "İ… "ŞŒ "ß– "â· "ã¾ "äÀ "åá "æâ "çé "èî "éï "êÿ "ë€!"ìÂ "í±!"î¸!"ï»!"ğÀ!"ñÁ!"òÈ!"óÍ!"ôÎ!"õÕ!"ö×!"÷á!"øâ!"ù½!"úŸ!"û  "ü  "ı  "ş  "ÿ  "€  "  "‚  "ƒê"„€#"…#"†ˆ#"‡#"ˆ#"‰™#"Šš#"Œ÷#"ø#"ÿ#"‰$"’ª$"“±$"”³$"•Ô$"–Õ$"—Ü$"˜á$"™â$"šò$"›ó$"œµ$"±%"¸%"Ÿ»%" À%"¡Á%"¢È%"£Í%"¤Î%"¥Õ%"¦×%"§á%"¨â%"©½%"ªŸ%"«“$"¬“$"­“$"®“$"¯“$"°“$"±“$"²“$"³İ#"´×""µ‚"¶†'"·'"¸’'"¹“'"º•'"»—'"¼¡'"½¢'"¾Ò'"ÀŞ'"Áß'"Âæ'"Ãğ'"ÆŒ("Ç("È("Éµ("Ê¼("ËÁ("ÌÂ("ÍÅ("ÎÈ("ÏÉ("ĞÏ("Ñø("Òÿ("Ó„)"Ô…)"Õ’)"Ö“)"×å("Ø½)"ÙÄ)"ÚÉ)"ÛÊ)"ÜÔ)"İÕ)"Şª)"ß’("àú'"áú'"âú'"ãú'"äú'"åú'"æú'"çú'"èÃ'"é©*"ê«*"ë­*"ì¾*"í¿*"îÆ*"ñæ*"òê*"óí*"ôî*"õô*"ö›+"÷©+"øª+"ùŠ+"úÒ+"ûİ+"üŞ+"ıÁ+"şÒ*"ÿÒ*"€Ò*"Ò*"‚Ò*"ƒÒ*"„Ò*"…Ò*"†¯*"‡Š,"ˆ‘,"‰œ,"Š,"‹Ÿ,"Œ¡,"¤,"«,"µ,"’Ğ,"“Û,"”Ü,"•¼,"–¼,"—¼,"˜¼,"™¼,"š¼,"›¼,"œû+"*"á&"Ÿğ" ğ"¡ğ"¢ğ"£ğ"¤ğ"¥ğ"¦ğ"¨ƒ."©„."ª‹."«•."®²."¯¹."°»."±è."²ï."³ô."´õ."µ‡/"¶ˆ/"·ä/"¸å/"¹ì/"ºñ/"»ò/"¼ƒ0"½„0"¾0"¿‘0"ÁÌ1"ÂÍ1"ÃÔ1"ÄŞ1"Ç…2"ÈŒ2"É2"Êµ2"Ë¶2"Ì½2"ÍÂ2"ÎÃ2"ÏÓ2"ĞÔ2"Ñ2"Ò‹3"Ó’3"Ô•3"Õš3"Ö›3"×¢3"Ø§3"Ù¨3"Ú¯3"Û±3"Ü»3"İ¼3"Ş—3"ßó2"àè1"áè1"âè1"ãè1"äè1"åè1"æè1"çè1"è¬1"éò4"êó4"ëú4"ìÿ4"í€5"î‘5"ï’5"ğ5"ñŸ5"ó‚6"ôƒ6"õŠ6"ö”6"ù»6"úÂ6"ûÄ6"üë6"ıì6"şó6"ÿø6"€ù6"‰7"‚Š7"ƒÆ6"„Î7"…Õ7"†Ø7"‡İ7"ˆŞ7"‰å7"Šê7"‹ë7"Œò7"ô7"ş7"ÿ7"Ú7"‘¶7"’6"“6"”6"•6"–6"—6"˜6"™6"šâ5"›½4"œŸ/"½9"Ä9"ŸÉ9" Ê9"¡Ù9"¢Ú9"£®:"¤¯:"¥¶:"¦»:"§¼:"¨Í:"©Î:"ªÕ:"«Ú:"¬Û:"­ê:"®ë:"¯ğ:"°ò:"±ı:"²ş:"´¹<"µº<"¶Á<"·Ë<"ºò<"»ù<"¼û<"½¢="¾£="¿ª="À¯="Á°="ÂÀ="ÃÁ="Äı<"Åø="Æÿ="Ç‚>"È‡>"Éˆ>"Ê>"Ë”>"Ì•>"Íœ>"Î>"Ï¨>"Ğ©>"Ñ„>"Òà="ÓÕ<"ÔÕ<"ÕÕ<"ÖÕ<"×Õ<"ØÕ<"ÙÕ<"ÚÕ<"Û™<"Üß?"İà?"Şç?"ßì?"àí?"áş?"âÿ?"ã†@"ä‹@"åŒ@"æ›@"çœ@"è¡@"é£@"ê®@"ë¯@"í’A"î“A"ïšA"ğ¤A"óËA"ôÒA"õÔA"öûA"÷üA"øƒB"ùˆB"ú‰B"û™B"üšB"ıÖA"şŞB"ÿåB"€èB"íB"‚îB"ƒõB"„úB"…ûB"†‚C"‡„C"ˆC"‰C"ŠêB"‹ÆB"Œ®A"®A"®A"®A"®A"‘®A"’®A"“®A"”ò@"•ª?"–é9"—9"˜½."™ÇD"›ÓD"œÔD"ÛD"åD"¡ÿD"¢E"£ƒE"¤©E"¥°E"¦µE"§¶E"¨¹E"©¼E"ª½E"«ÃE"¬êE"­ñE"®öE"¯÷E"°„F"±…F"²ÙE"³­F"´´F"µ¹F"¶ºF"·ÄF"¸ÅF"¹œF"ºŠE"»ïD"¼ïD"½ïD"¾ïD"¿ïD"ÀïD"ÁïD"ÂïD"ÃºD"ÄŸ."ÅŸ."ÆŸ."ÇŸ."ÈŸ."ÉŸ."ÊŸ."ËŸ."Ìå-"Íº"Îâ"Ï†"Ğ†"Ñ†"Ò†"Ó†"Ô†"Õ†"Ö†"×n